language: node_js

node_js:
  - node

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t $DOCKER_USERNAME/$PROJECT_NAME .
  - docker push $PROJECT_NAME:$PROJECT_VERSION

branches:
  only:
    - master