apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: events-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
#    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /events(/|$)(.*)
            backend:
              serviceName: events
              servicePort: 80