apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: events
  template:
    metadata:
      labels:
        app: events
    spec:
      containers:
      - image: ribvid/rso-events:1.0.6
        name: events
        env:
        - name: CONSUL
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        ports:
        - containerPort: 3000
          name: server
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: events
spec:
#  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: events
