apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-deployment
spec:
  selector:
    matchLabels:
      app: events
  template:
    metadata:
      labels:
        app: events
    spec:
      containers:
        - image: ribvid/rso-events:1.0.7
          name: events
          env:
            - name: SPM_TOKEN
              value: "1808ad59-dfc7-40da-ab1a-3880d0880f9e"
            - name: RABBITMQ
              value: "amqp://xhynquga:TsoWIxuD8ZRXu0Mjq0qrB-IEdOUJgDfs@stingray.rmq.cloudamqp.com/xhynquga"
            - name: ROARR_LOG
              value: "true"
            - name: NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: VERSION
              value: 1.0.7
            - name: CONSUL
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /live
              port: 9000
            failureThreshold: 2
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 9000
            initialDelaySeconds: 5
            failureThreshold: 2
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: events
spec:
  #  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: events
---
apiVersion: v1
kind: Service
metadata:
  name: events-health
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9000
  selector:
    app: events
